### ISSUE TITLE
Internal Error on Upload\Convert

### ISSUE THREAD

**Issue by tranzaction** [Griboedow/PandocUltimateConverter#2] opened 2024-03-19 13:24 UTC
Hesitant to post, incase its something unique with my setup but, using latest XAMPP as the stack for testing this extension in mediawiki, i've come across an internal error when trying to upload and convert. 

Stacktrace details below, and hoping these might be useful.

_[f4c0923d8d4858b2cd7f07c1] /mediawiki/index.php/Special:PandocUltimateConverter Error: Call to a member function getLocalRefPath() on bool

Backtrace:

```
from C:\xampp\htdocs\mediawiki\extensions\PandocUltimateConverter\SpecialPandocUltimateConverter.php(119)
#0 C:\xampp\htdocs\mediawiki\extensions\PandocUltimateConverter\SpecialPandocUltimateConverter.php(84): SpecialPandocUltimateConverter::convertFileToPage(string, string)
#1 C:\xampp\htdocs\mediawiki\includes\htmlform\HTMLForm.php(751): SpecialPandocUltimateConverter::processForm(array, HTMLForm)
#2 C:\xampp\htdocs\mediawiki\includes\htmlform\HTMLForm.php(631): HTMLForm->trySubmit()
#3 C:\xampp\htdocs\mediawiki\includes\htmlform\HTMLForm.php(647): HTMLForm->tryAuthorizedSubmit()
#4 C:\xampp\htdocs\mediawiki\extensions\PandocUltimateConverter\SpecialPandocUltimateConverter.php(75): HTMLForm->show()
#5 C:\xampp\htdocs\mediawiki\includes\specialpage\SpecialPage.php(727): SpecialPandocUltimateConverter->execute(NULL)
#6 C:\xampp\htdocs\mediawiki\includes\specialpage\SpecialPageFactory.php(1621): MediaWiki\SpecialPage\SpecialPage->run(NULL)
#7 C:\xampp\htdocs\mediawiki\includes\MediaWiki.php(357): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#8 C:\xampp\htdocs\mediawiki\includes\MediaWiki.php(960): MediaWiki->performRequest()
#9 C:\xampp\htdocs\mediawiki\includes\MediaWiki.php(613): MediaWiki->main()
#10 C:\xampp\htdocs\mediawiki\index.php(50): MediaWiki->run()
#11 C:\xampp\htdocs\mediawiki\index.php(46): wfIndexMain()
#12 {main}_
```

**Comment by Griboedow** [comment] 2024-03-19 14:40
Thanks for the report. WIll take a look next week


Upload itself is done via JS, so may I ask you to check what do you have in browser console? And which browser fdo you use?

**Comment by tranzaction** [comment] 2024-03-20 11:32
When i next get the chance, i'll have a look at the console.   This was tested with both edge and chrome.
Failed to mention this was a Windows 11 Pro environment running Xampp,  as part of local test of MediaWiki.

**Comment by Griboedow** [comment] 2024-03-27 10:21
I will try to add some error handling to JS code so the issue would be visible during the upload.

**Comment by Griboedow** [comment] 2024-03-27 11:13
I've added the error handling. May I ask you to check the new version?

JS error will be visible in the alert like this one:
![image](https://github.com/Griboedow/PandocUltimateConverter/assets/4194526/46ea367d-182c-4dae-a448-5c96e0132949)

Commit 2fd6b9009a071f8344f8c04b2c2777e252cb1368

**Comment by Griboedow** [comment] 2024-07-28 11:21
Closing the issue since we have not heard from you for a while.

If the issue reproduces again, geel free to reopen the issue.

**Closed** 2024-07-28 11:21 UTC
Labels: bug
